project_id = "vtbxyjroscevdsqihikn"

[functions.trackers]
verify_jwt = true

[functions.products]
verify_jwt = true

[functions.scraper]
verify_jwt = false

[functions.admin]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false

[functions.update-all-prices]
verify_jwt = false